# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Python checks

on:
  pull_request:
    paths:
      - "python/**"
      - "spec/**"
      - ".github/workflows/python.yml"
jobs:
  python-checks:
    runs-on: ubuntu-latest
    env:
      PATH: ${{ github.workspace }}/go/bin:${{ github.workspace }}/.cargo/bin:${{ github.workspace }}/.local/share/pnpm:${{ github.workspace }}/.local/bin:/usr/local/bin:/usr/bin:/bin
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "pypy-3.10"
          - "pypy-3.11"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: stable

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install uv and setup Python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Format check
        run: uv run --active --directory python ruff format --check --preview .

      - name: Lint with ruff
        run: uv run --active --directory python ruff check --select I .

      - name: Static type check
        run: uv run --active --directory python mypy .

      # TODO: Move this to a rust workflow once we have one.
      - name: Run rust lint
        run: pushd python/handlebarrz && cargo clippy --all-targets --all-features -- -D warnings && popd

      - name: Check licenses
        run: ./scripts/check_license

      - name: Run Rust checks for handlebarrz
        run: ./scripts/run_handlebarrz_checks

      - name: Build Rust extension for Python ${{ matrix.python-version }}
        working-directory: ./python
        run: |
          uv run --python ${{ matrix.python-version }} --active --isolated --directory handlebarrz maturin develop

      - name: Run Python tests for Python ${{ matrix.python-version }}
        working-directory: ./python
        run: |
          uv run --python ${{ matrix.python-version }} --active --isolated pytest -xvvs --log-level=DEBUG .

      - name: Build distributions
        run: ./scripts/build_dists
